Permessage-deflate
swimos/tungstenite-rs pull request #1
Opened 2020-09-17 08:54 UTC by SirCipher

2020-09-17 14:18 UTC, horned-sphere requested changes
Looks really nice. Just a few niggles.

2020-09-17 14:18 UTC, horned-sphere commented on src/client.rs
> +    E: WebSocketExtension,
Mixture of parameter place constraints and where clause constraints is a bit messy.

2020-09-17 14:18 UTC, horned-sphere commented on src/client.rs
> +pub fn connect_with_config<Req: IntoClientRequest, E>(
I'd make this more descriptive than "E".

2020-09-17 14:18 UTC, horned-sphere commented on src/error.rs
> +    ExtensionError(Box<dyn std::error::Error + Send + Sync>),
They might not like having boxed arbitrary errors here. It might be necesary to turn them into Cows as for some of the other variants. Worth a try though.

2020-09-17 14:18 UTC, horned-sphere commented on src/extensions/deflate.rs
> +    compression_level: Compression,
Should probably document all of the configuration if you're doing any of it.

2020-09-17 14:18 UTC, horned-sphere commented on src/extensions/deflate.rs
> +            max_window_bits: 15,
This should be a named constant (and the choice of 15 explained).

2020-09-17 14:18 UTC, horned-sphere commented on src/extensions/deflate.rs
> +            max_window_bits: 15,
As above.

2020-09-17 14:18 UTC, horned-sphere commented on src/extensions/deflate.rs
> +            ..Default::default()
I didn't realise you could do that. Both cool and horrifying :D

2020-09-17 14:18 UTC, horned-sphere commented on src/extensions/deflate.rs
> +}
This looks a bit dodgy (presuming the inflators and deflators are stateful). It seems a bit against the spirit of Clone.

2020-09-17 14:18 UTC, horned-sphere commented on src/extensions/uncompressed.rs
> +
Why only plain text and not binary?

2020-09-17 14:18 UTC, horned-sphere commented on src/protocol/frame/mod.rs
> +
More reformatting.

2020-09-17 14:19 UTC, SirCipher commented on Cargo.toml
> +flate2 = { version = "1.0", features = ["zlib"], default-features = false }
I suppose it could be as it's a bit more involved :)

2020-09-17 14:21 UTC, SirCipher commented on autobahn/client-results.json
> +         "duration": 3,
These results files are what is run on CI to check that the implementation matches the Autobahn test suite. The test results are asserted against in the script with the duration fields ignored: https://github.com/swimos/tungstenite-rs/blob/master/scripts/autobahn-client.sh#L16 Further down in this file there are the permessage-deflate tests and they have been changed from saying `UNIMPLEMENTED` to `OK`.

2020-09-17 14:26 UTC, SirCipher commented on examples/autobahn-client.rs
> +    let (mut socket, _): (WebSocket<_, PlainTextExt>, _) = connect_with_config(
Ah, it's not anymore actually. I forgot to change the function call. It was required as no configuration object was passed in and it couldn't work out which extension was being used.

2020-09-17 14:27 UTC, SirCipher commented on scripts/autobahn-server.sh
> +        <(jq -S 'del(."Tungstenite" | .. | .duration?)' 'autobahn/server-results.json') \
Yeah, both the client and the server scripts were reading the client results.

2020-09-17 14:31 UTC, SirCipher commented on src/extensions/uncompressed.rs
> +
Perhaps the name of this structure is misleading. This is an uncompressed extension

2020-09-17 14:31 UTC, SirCipher commented on src/extensions/deflate.rs
> +}
Yeah, I can see what you mean. I'll look at refactoring it into something nicer, as there are a couple of other points in this process that I'm not too keen on

2020-09-17 16:06 UTC, SirCipher commented on src/extensions/deflate.rs
> +            ..Default::default()
It's quite useful :)

2020-09-18 12:55 UTC, horned-sphere commented on .gitignore
> +.idea
They might not appreciate you adding InitelliJ specific stuff to .gitignore. I'd advise just pitting it in your git exclude file.

2020-09-24 09:09 UTC, horned-sphere approved these changes

2020-09-24 11:35 UTC, DobromirM approved these changes

2020-09-24 11:35 UTC, DobromirM commented on fuzz/fuzz_targets/read_message_client.rs
> +});
Missing newline at the end of the file.

2020-09-24 12:16 UTC, merged